######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 27 19:31:53 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp

CONFIG -= qt
CONFIG += debug
QMAKE_CLEAN += $(TARGET)
