######################################################################
# Automatically generated by qmake (1.07a) Tue Apr 9 15:23:31 2013
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += acoustic.h auxiliary.h global_var.h stencil.h sysTime.h
SOURCES += acoustic.cpp auxiliary.cpp global_var.cpp main.cpp sysTime.cpp

CONFIG -= qt

QMAKE_CLEAN += $(TARGET)
